[package]
name = "scrmiror"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
hex = "0.4.3"
rusb = "0.9.1"
rusty_libimobiledevice = "0.1.3"